---
- name: Install required s/w's on devserver
  hosts: devserver
  tasks: 
    - name: Install required s/w's
      apt:
        name: "{{item.a}}"
        state: "{{item.b}}"
        update_cache: "{{item.c}}"
      with_items:
        - {a: openjdk-11-jdk,b: present,c: yes}
        - {a: git,b: present,c: no}
        - {a: maven,b: present,c: no}
- name: Install required s/w'on qaserver
  hosts: qaserver
  tasks:
    - name: Install required s/w's
      apt:
        name: "{{item.a}}"
        state: "{{item.b}}"
        update_cache: "{{item.c}}"
      with_items:
        - {a: git,b: present,c: no}
        - {a: openjdk-11-jdk,b: present,c: yes}
        - {a: tomcat9,b: present,c: no}
        - {a: tomcat9-admin,b: present,c: no}
- name: Install required s/w'on prodserver
  hosts: prodserver
  tasks:
    - name: Install required s/w's
      apt:
        name: "{{item.a}}"
        state: "{{item.b}}"
        update_cache: "{{item.c}}"
      with_items:
        - {a: tomcat9,b: present,c: yes}
        - {a: tomcat9-admin,b: present,c: yes}
- name: continious download and continious build
  hosts: devserver
  tasks:
    - name: Download the devcode from github
      git:
        repo: https://github.com/intelliqittrainings/maven.git
        dest: dev-git
    - name: create artifact
      shell: cd dev-git;mvn package
    - name: fetch the artifact from devserver to controller
      fetch:
        src: dev-git/webapp/target/webapp.war
        dest: /tmp
- name: Continious Deployment and continious testing
  hosts: qaserver
  tasks:
    - name: deploy artifact into tomcat on qaserver
      copy:
        src: /tmp/172.31.18.220/dev-git/webapp/target/webapp.war
        dest: /var/lib/tomcat9/webapps/testapp.war
    - name: Download the selenium scripts
      git:
        repo: https://github.com/intelliqittrainings/FunctionalTesting.git
        dest: test-git
    - name: Run the selenium scripts
      shell: java -jar test-git/testing.jar
- name: continious Delivery
  hosts: prodserver
  tasks:
    - name: Deploy artifact into tomcat on prodserver
      copy:
        src: /tmp/172.31.18.220/dev-git/webapp/target/webapp.war
        dest: /var/lib/tomcat9/webapps/prodapp.war




...          



