---
- name: Configuring apache using child playbooks
  hosts: all
  tasks:
    - name: call multiple child playbooks
      include_tasks: "{{item}}"
      with_items:
        - install_apache.yml
        - edit_index.yml
        - restart.yml
        - check_url_response.yml

...
