---
- name: Capture Os Info
  hosts: all
  tasks:
    - name: Capture Os name
      debug:
        msg: "{{ansible_distribution}}"
    - name: Capture Os version no
      debug:
        msg: "{{ansible_distribution_version}}"
    - name: Capture Os major version no
      debug:    
        msg: "{{ansible_distribution_major_version}}"    


...

