---
- name: Install apache2/httpd on ubuntu and redhat servers
  hosts: all
  tasks:
    - name: Install apache2 on ubuntu servers
      apt:
        name: git
        state: present
        update_cache: yes
      when: ansible_distribution == "Ubuntu"
    - name: Install httpd on RHEL servers
      yum:
        name: httpd
        state: present
        update_cache: yes
      when: ansible_distribution == "RedHat"
    - name: edit the index.html file
      copy:
        content: :welcome to intelliqit"
        dest: /var/www/html/index.html
    - name: Restart apache2 on ubuntu servers
      service:
        name: apache2
        state: restarted
      when: ansible_distribution == "Ubuntu"
    - name: Restart httpd on RHEL servers
      service:
        name: httpd
        state: restarted
      when: ansible_distribution == "RedHat"
    - name: Check if apache2/httpd is responding
      uri:
        url: "{{item}}"
        status_code: 200
      with_items:
        - http://172.31.15.219
        - http://172.31.23.31
        - http://172.31.26.126


...
