---
- name: create user on all servers
  hosts: all
  serial: 1
  tasks:
    - name: user creation
      user:
        name: Anusha
        password: Adinesh
        home: /home/Anusha
        uid: 1234
        shell: /bin/bash
        comment: "a normal user"

...          
