---
- name: create users and file/dirs in users home
  hosts: all
  tasks:
    - name: create users
      user:
        name: "{{a}}"
        password: "{{b}}"
        home: "{{c}}"
    - name: create files/dirs in users home
      file:
        name: "{{d}}"
        state: "{{e}}"

...          
