---
- name: Implementing when condition
  hosts: all
  vars:
    - a: 10
  tasks:
    - name: create directory
      file:
        name: /tmp/dir1
        state: directory
      when: a==10

...        
