---
- name: create users and copy files into user home dirs
  hosts: all
  tasks:
    - name: create users
      user:
        name: "{{item.a}}"
        password: "{{item.b}}"
        home: "{{item.c}}"
      with_items:
        - {a: anusha,b: anusha,c: /tmp/anusha}
        - {a: dinesh,b: dinesh,c: /home/dinesh}
    - name: copy files into users home dirs
      copy:
        src: "{{item.a}}"
        dest: "{{item.b}}"
      with_items:
        - {a: /etc/passwd,b: /tmp/anusha}
        - {a: /etc/group,b: /home/dinesh}


...          

